default_context:
  project_name: 'my-first-app-fastapi'
  project_slug: 'py-fastapi'
  domain_main: 'development'
  domain_staging: 'pre-test'
  docker_swarm_stack_name_main: 'development'
  docker_swarm_stack_name_staging: 'pre-test'
  secret_key: '99d3b1f01aa639e4a76f4fc281fc834747a543720ba4c8a8648ba755aef9be7f'
  first_superuser: 'admin@gmail.com'
  first_superuser_password: 'admin'
  backend_cors_origins: ["http://localhost:8070", "http://localhost", "http://localhost:80", "http://localhost:8080", "http://localhost:5555"]
  smtp_port: '587'
  smtp_host: 'gmail'
  smtp_user: 'example@gmail.com'
  smtp_password: ''
  smtp_emails_from_email: 'example@gmail.com'
  postgres_password: 'changethis'
  pgadmin_default_user: 'admin'
  pgadmin_default_user_password: 'admin'
  traefik_constraint_tag: 'development'
  traefik_constraint_tag_staging: 'pre-test'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:admin'
  sentry_dsn: ''
  docker_image_prefix: 'github.com/tbr0117/python-full-stack-fastapi-postgresql'
  docker_image_backend: 'github.com/tbr0117/python-full-stack-fastapi-postgresql/backend'
  docker_image_celeryworker: 'github.com/tbr0117/python-full-stack-fastapi-postgresqlceleryworker'
  docker_image_frontend: 'github.com/tbr0117/python-full-stack-fastapi-postgresql/frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
